apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-jetson-exporter
spec:
  podSelector:
    matchLabels:
      app: jetson-exporter
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 8000
