apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kube-state-metrics
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}  # 모든 네임스페이스에서
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8081
